#include "board.h"

const char __attribute__ ((section(".custom_defaults"), used, aligned(4))) customDefaults[] = 
    "# Betaflight\n"
    "board_name H743\n"
    "manufacturer_id CUST\n"
    "# name: VT40-2 V2\n"
    "# resources\n"
    "resource BEEPER 1 B07\n"
    "resource MOTOR 1 A00\n"
    "resource MOTOR 2 A01\n"
    "resource MOTOR 3 A02\n"
    "resource MOTOR 4 A03\n"
    "resource MOTOR 5 B00\n"
    "resource MOTOR 6 B01\n"
    "resource MOTOR 7 B04\n"
    "resource MOTOR 8 B03\n"
    "resource SERVO 1 D14\n"
    "resource SERVO 2 D15\n"
    "resource SERVO 3 NONE\n"
    "resource SERVO 4 NONE\n"
    "resource SERVO 5 NONE\n"
    "resource SERVO 6 NONE\n"
    "resource SERVO 7 NONE\n"
    "resource SERVO 8 NONE\n"
    "resource PPM 1 NONE\n"
    "resource PWM 1 NONE\n"
    "resource PWM 2 NONE\n"
    "resource PWM 3 NONE\n"
    "resource PWM 4 NONE\n"
    "resource PWM 5 NONE\n"
    "resource PWM 6 NONE\n"
    "resource PWM 7 NONE\n"
    "resource PWM 8 NONE\n"
    "resource SONAR_TRIGGER 1 NONE\n"
    "resource SONAR_ECHO 1 NONE\n"
    "resource LED_STRIP 1 A08\n"
    "resource SERIAL_TX 1 A09\n"
    "resource SERIAL_TX 2 D05\n"
    "resource SERIAL_TX 3 D08\n"
    "resource SERIAL_TX 4 D01\n"
    "resource SERIAL_TX 5 B06\n"
    "resource SERIAL_TX 6 C06\n"
    "resource SERIAL_TX 7 E08\n"
    "resource SERIAL_TX 8 E01\n"
    "resource SERIAL_TX 9 NONE\n"
    "resource SERIAL_TX 10 NONE\n"
    "resource SERIAL_RX 1 A10\n"
    "resource SERIAL_RX 2 D06\n"
    "resource SERIAL_RX 3 D09\n"
    "resource SERIAL_RX 4 D00\n"
    "resource SERIAL_RX 5 B05\n"
    "resource SERIAL_RX 6 C07\n"
    "resource SERIAL_RX 7 E07\n"
    "resource SERIAL_RX 8 E00\n"
    "resource SERIAL_RX 9 NONE\n"
    "resource SERIAL_RX 10 NONE\n"
    "resource SOFTSERIAL_TX 1 NONE\n"
    "resource SOFTSERIAL_TX 2 NONE\n"
    "resource SOFTSERIAL_RX 1 NONE\n"
    "resource SOFTSERIAL_RX 2 NONE\n"
    "resource LPUART_TX 1 NONE\n"
    "resource LPUART_RX 1 NONE\n"
    "resource I2C_SCL 1 NONE\n"
    "resource I2C_SCL 2 B10\n"
    "resource I2C_SCL 3 NONE\n"
    "resource I2C_SCL 4 D12\n"
    "resource I2C_SDA 1 NONE\n"
    "resource I2C_SDA 2 B11\n"
    "resource I2C_SDA 3 NONE\n"
    "resource I2C_SDA 4 D13\n"
    "resource LED 1 E05\n"
    "resource LED 2 E04\n"
    "resource LED 3 E02\n"
    "resource RX_BIND 1 NONE\n"
    "resource RX_BIND_PLUG 1 NONE\n"
    "resource TRANSPONDER 1 NONE\n"
    "resource SPI_SCK 1 A05\n"
    "resource SPI_SCK 2 B13\n"
    "resource SPI_SCK 3 NONE\n"
    "resource SPI_SCK 4 E12\n"
    "resource SPI_SCK 5 NONE\n"
    "resource SPI_SCK 6 NONE\n"
    "resource SPI_SDI 1 A06\n"
    "resource SPI_SDI 2 B14\n"
    "resource SPI_SDI 3 NONE\n"
    "resource SPI_SDI 4 E13\n"
    "resource SPI_SDI 5 NONE\n"
    "resource SPI_SDI 6 NONE\n"
    "resource SPI_SDO 1 A07\n"
    "resource SPI_SDO 2 B15\n"
    "resource SPI_SDO 3 NONE\n"
    "resource SPI_SDO 4 E14\n"
    "resource SPI_SDO 5 NONE\n"
    "resource SPI_SDO 6 NONE\n"
    "resource ESCSERIAL 1 NONE\n"
    "resource ADC_BATT 1 C01\n"
    "resource ADC_RSSI 1 C05\n"
    "resource ADC_CURR 1 C03\n"
    "resource ADC_EXT 1 C04\n"
    "resource BARO_CS 1 NONE\n"
    "resource BARO_EOC 1 NONE\n"
    "resource BARO_XCLR 1 NONE\n"
    "resource COMPASS_CS 1 NONE\n"
    "resource COMPASS_EXTI 1 NONE\n"
    "resource SDCARD_CS 1 NONE\n"
    "resource SDCARD_DETECT 1 NONE\n"
    "resource SDIO_CK 1 C12\n"
    "resource SDIO_CMD 1 D02\n"
    "resource SDIO_D0 1 C08\n"
    "resource SDIO_D1 1 C09\n"
    "resource SDIO_D2 1 C10\n"
    "resource SDIO_D3 1 C11\n"
    "resource PINIO 1 E10\n"
    "resource PINIO 2 B05\n"
    "resource PINIO 3 NONE\n"
    "resource PINIO 4 NONE\n"
    "resource USB_MSC_PIN 1 NONE\n"
    "resource OSD_CS 1 B12\n"
    "resource GYRO_EXTI 1 E09\n"
    "resource GYRO_EXTI 2 E15\n"
    "resource GYRO_CS 1 A04\n"
    "resource GYRO_CS 2 E11\n"
    "resource USB_DETECT 1 NONE\n"
    "resource VTX_POWER 1 NONE\n"
    "resource VTX_CS 1 NONE\n"
    "resource VTX_DATA 1 NONE\n"
    "resource VTX_CLK 1 NONE\n"
    "resource PULLUP 1 NONE\n"
    "resource PULLUP 2 NONE\n"
    "resource PULLUP 3 NONE\n"
    "resource PULLUP 4 NONE\n"
    "resource PULLDOWN 1 NONE\n"
    "resource PULLDOWN 2 NONE\n"
    "resource PULLDOWN 3 NONE\n"
    "resource PULLDOWN 4 NONE\n"
    "# timer\n"
    "timer A00 AF1\n"
    "timer A01 AF1\n"
    "timer A02 AF1\n"
    "timer A03 AF1\n"
    "timer B00 AF1\n"
    "timer B01 AF1\n"
    "timer D14 AF2\n"
    "timer D15 AF2\n"
    "timer A08 AF1\n"
    "timer B05 AF2\n"
    "# dma\n"
    "dma SPI_SDO 1 NONE\n"
    "dma SPI_SDO 2 NONE\n"
    "dma SPI_SDO 3 NONE\n"
    "dma SPI_SDO 4 NONE\n"
    "dma SPI_SDO 5 NONE\n"
    "dma SPI_SDO 6 NONE\n"
    "dma SPI_SDI 1 NONE\n"
    "dma SPI_SDI 2 NONE\n"
    "dma SPI_SDI 3 NONE\n"
    "dma SPI_SDI 4 NONE\n"
    "dma SPI_SDI 5 NONE\n"
    "dma SPI_SDI 6 NONE\n"
    "dma SPI_TX 1 NONE\n"
    "dma SPI_TX 2 NONE\n"
    "dma SPI_TX 3 NONE\n"
    "dma SPI_TX 4 NONE\n"
    "dma SPI_TX 5 NONE\n"
    "dma SPI_TX 6 NONE\n"
    "dma SPI_RX 1 NONE\n"
    "dma SPI_RX 2 NONE\n"
    "dma SPI_RX 3 NONE\n"
    "dma SPI_RX 4 NONE\n"
    "dma SPI_RX 5 NONE\n"
    "dma SPI_RX 6 NONE\n"
    "dma ADC 1 4\n"
    "dma ADC 2 5\n"
    "dma ADC 3 6\n"
    "dma UART_TX 1 NONE\n"
    "dma UART_TX 2 NONE\n"
    "dma UART_TX 3 NONE\n"
    "dma UART_TX 4 NONE\n"
    "dma UART_TX 5 NONE\n"
    "dma UART_TX 6 NONE\n"
    "dma UART_TX 7 NONE\n"
    "dma UART_TX 8 NONE\n"
    "dma UART_TX 9 NONE\n"
    "dma UART_TX 10 NONE\n"
    "dma UART_TX 11 NONE\n"
    "dma UART_RX 1 NONE\n"
    "dma UART_RX 2 NONE\n"
    "dma UART_RX 3 NONE\n"
    "dma UART_RX 4 NONE\n"
    "dma UART_RX 5 NONE\n"
    "dma UART_RX 6 NONE\n"
    "dma UART_RX 7 NONE\n"
    "dma UART_RX 8 NONE\n"
    "dma UART_RX 9 NONE\n"
    "dma UART_RX 10 NONE\n"
    "dma UART_RX 11 NONE\n"
    "dma TIMUP 1 NONE\n"
    "dma TIMUP 2 0\n"
    "dma TIMUP 3 1\n"
    "dma TIMUP 4 3\n"
    "dma TIMUP 5 NONE\n"
    "dma TIMUP 6 NONE\n"
    "dma TIMUP 7 NONE\n"
    "dma TIMUP 8 2\n"
    "dma TIMUP 15 NONE\n"
    "dma TIMUP 16 NONE\n"
    "dma TIMUP 17 NONE\n"
    "dma pin A00 0\n"
    "dma pin A01 0\n"
    "dma pin A02 0\n"
    "dma pin A03 0\n"
    "dma pin B00 1\n"
    "dma pin B01 1\n"
    "dma pin D14 2\n"
    "dma pin D15 NONE\n"
    "dma pin A08 3\n"
    "dma pin B05 3\n"
    "# feature\n"
    "feature -RX_PPM\n"
    "feature -INFLIGHT_ACC_CAL\n"
    "feature -RX_SERIAL\n"
    "feature -MOTOR_STOP\n"
    "feature -SERVO_TILT\n"
    "feature -SOFTSERIAL\n"
    "feature -GPS\n"
    "feature -RANGEFINDER\n"
    "feature -TELEMETRY\n"
    "feature -3D\n"
    "feature -RX_PARALLEL_PWM\n"
    "feature -RX_MSP\n"
    "feature -RSSI_ADC\n"
    "feature -LED_STRIP\n"
    "feature -DISPLAY\n"
    "feature -OSD\n"
    "feature -CHANNEL_FORWARDING\n"
    "feature -TRANSPONDER\n"
    "feature -AIRMODE\n"
    "feature -RX_SPI\n"
    "feature -ESC_SENSOR\n"
    "feature -ANTI_GRAVITY\n"
    "feature RX_SERIAL\n"
    "feature SOFTSERIAL\n"
    "feature RANGEFINDER\n"
    "feature TELEMETRY\n"
    "feature LED_STRIP\n"
    "feature DISPLAY\n"
    "feature OSD\n"
    "feature CHANNEL_FORWARDING\n"
    "feature TRANSPONDER\n"
    "feature AIRMODE\n"
    "feature ANTI_GRAVITY\n"
    "# serial\n"
    "serial 20 1 115200 57600 0 115200\n"
    "serial 0 0 115200 57600 0 115200\n"
    "serial 1 0 115200 57600 0 115200\n"
    "serial 2 0 115200 57600 0 115200\n"
    "serial 3 0 115200 57600 0 115200\n"
    "serial 4 0 115200 57600 0 115200\n"
    "serial 5 0 115200 57600 0 115200\n"
    "serial 6 64 115200 57600 0 115200\n"
    "serial 7 0 115200 57600 0 115200\n"
    "# mixer\n"
    "mixer QUADX\n"
    "mmix reset\n"
    "# servo\n"
    "servo 0 1000 2000 1500 100 -1\n"
    "servo 1 1000 2000 1500 100 -1\n"
    "servo 2 1000 2000 1500 100 -1\n"
    "servo 3 1000 2000 1500 100 -1\n"
    "servo 4 1000 2000 1500 100 -1\n"
    "servo 5 1000 2000 1500 100 -1\n"
    "servo 6 1000 2000 1500 100 -1\n"
    "servo 7 1000 2000 1500 100 -1\n"
    "# servo mixer\n"
    "smix reset\n"
    "# beeper\n"
    "beeper GYRO_CALIBRATED\n"
    "beeper RX_LOST\n"
    "beeper RX_LOST_LANDING\n"
    "beeper DISARMING\n"
    "beeper ARMING\n"
    "beeper ARMING_GPS_FIX\n"
    "beeper ARMING_GPS_NO_FIX\n"
    "beeper BAT_CRIT_LOW\n"
    "beeper BAT_LOW\n"
    "beeper GPS_STATUS\n"
    "beeper RX_SET\n"
    "beeper ACC_CALIBRATION\n"
    "beeper ACC_CALIBRATION_FAIL\n"
    "beeper READY_BEEP\n"
    "beeper MULTI_BEEPS\n"
    "beeper DISARM_REPEAT\n"
    "beeper ARMED\n"
    "beeper SYSTEM_INIT\n"
    "beeper ON_USB\n"
    "beeper BLACKBOX_ERASE\n"
    "beeper CRASH_FLIP\n"
    "beeper CAM_CONNECTION_OPEN\n"
    "beeper CAM_CONNECTION_CLOSE\n"
    "beeper RC_SMOOTHING_INIT_FAIL\n"
    "# beacon\n"
    "beacon -RX_LOST\n"
    "beacon -RX_SET\n"
    "# map\n"
    "map TAER1234\n"
    "# led\n"
    "led 0 0,0::C:0\n"
    "led 1 0,0::C:0\n"
    "led 2 0,0::C:0\n"
    "led 3 0,0::C:0\n"
    "led 4 0,0::C:0\n"
    "led 5 0,0::C:0\n"
    "led 6 0,0::C:0\n"
    "led 7 0,0::C:0\n"
    "led 8 0,0::C:0\n"
    "led 9 0,0::C:0\n"
    "led 10 0,0::C:0\n"
    "led 11 0,0::C:0\n"
    "led 12 0,0::C:0\n"
    "led 13 0,0::C:0\n"
    "led 14 0,0::C:0\n"
    "led 15 0,0::C:0\n"
    "led 16 0,0::C:0\n"
    "led 17 0,0::C:0\n"
    "led 18 0,0::C:0\n"
    "led 19 0,0::C:0\n"
    "led 20 0,0::C:0\n"
    "led 21 0,0::C:0\n"
    "led 22 0,0::C:0\n"
    "led 23 0,0::C:0\n"
    "led 24 0,0::C:0\n"
    "led 25 0,0::C:0\n"
    "led 26 0,0::C:0\n"
    "led 27 0,0::C:0\n"
    "led 28 0,0::C:0\n"
    "led 29 0,0::C:0\n"
    "led 30 0,0::C:0\n"
    "led 31 0,0::C:0\n"
    "# color\n"
    "color 0 0,0,0\n"
    "color 1 0,255,255\n"
    "color 2 0,0,255\n"
    "color 3 30,0,255\n"
    "color 4 60,0,255\n"
    "color 5 90,0,255\n"
    "color 6 120,0,255\n"
    "color 7 150,0,255\n"
    "color 8 180,0,255\n"
    "color 9 210,0,255\n"
    "color 10 240,0,255\n"
    "color 11 270,0,255\n"
    "color 12 300,0,255\n"
    "color 13 330,0,255\n"
    "color 14 0,0,0\n"
    "color 15 0,0,0\n"
    "# mode_color\n"
    "mode_color 0 0 1\n"
    "mode_color 0 1 11\n"
    "mode_color 0 2 2\n"
    "mode_color 0 3 13\n"
    "mode_color 0 4 10\n"
    "mode_color 0 5 3\n"
    "mode_color 1 0 5\n"
    "mode_color 1 1 11\n"
    "mode_color 1 2 3\n"
    "mode_color 1 3 13\n"
    "mode_color 1 4 10\n"
    "mode_color 1 5 3\n"
    "mode_color 2 0 10\n"
    "mode_color 2 1 11\n"
    "mode_color 2 2 4\n"
    "mode_color 2 3 13\n"
    "mode_color 2 4 10\n"
    "mode_color 2 5 3\n"
    "mode_color 3 0 8\n"
    "mode_color 3 1 11\n"
    "mode_color 3 2 4\n"
    "mode_color 3 3 13\n"
    "mode_color 3 4 10\n"
    "mode_color 3 5 3\n"
    "mode_color 4 0 7\n"
    "mode_color 4 1 11\n"
    "mode_color 4 2 3\n"
    "mode_color 4 3 13\n"
    "mode_color 4 4 10\n"
    "mode_color 4 5 3\n"
    "mode_color 5 0 0\n"
    "mode_color 5 1 0\n"
    "mode_color 5 2 0\n"
    "mode_color 5 3 0\n"
    "mode_color 5 4 0\n"
    "mode_color 5 5 0\n"
    "mode_color 6 0 6\n"
    "mode_color 6 1 10\n"
    "mode_color 6 2 1\n"
    "mode_color 6 3 0\n"
    "mode_color 6 4 0\n"
    "mode_color 6 5 2\n"
    "mode_color 6 6 3\n"
    "mode_color 6 7 6\n"
    "mode_color 6 8 0\n"
    "mode_color 6 9 0\n"
    "mode_color 6 10 0\n"
    "mode_color 7 0 3\n"
    "# aux\n"
    "aux 0 0 0 1625 2100 0 0\n"
    "aux 1 0 0 900 900 0 0\n"
    "aux 2 0 0 900 900 0 0\n"
    "aux 3 0 0 900 900 0 0\n"
    "aux 4 0 0 900 900 0 0\n"
    "aux 5 0 0 900 900 0 0\n"
    "aux 6 0 0 900 900 0 0\n"
    "aux 7 0 0 900 900 0 0\n"
    "aux 8 0 0 900 900 0 0\n"
    "aux 9 0 0 900 900 0 0\n"
    "aux 10 0 0 900 900 0 0\n"
    "aux 11 0 0 900 900 0 0\n"
    "aux 12 0 0 900 900 0 0\n"
    "aux 13 0 0 900 900 0 0\n"
    "aux 14 0 0 900 900 0 0\n"
    "aux 15 0 0 900 900 0 0\n"
    "aux 16 0 0 900 900 0 0\n"
    "aux 17 0 0 900 900 0 0\n"
    "aux 18 0 0 900 900 0 0\n"
    "aux 19 0 0 900 900 0 0\n"
    "# adjrange\n"
    "adjrange 0 0 0 900 900 0 0 0 0\n"
    "adjrange 1 0 0 900 900 0 0 0 0\n"
    "adjrange 2 0 0 900 900 0 0 0 0\n"
    "adjrange 3 0 0 900 900 0 0 0 0\n"
    "adjrange 4 0 0 900 900 0 0 0 0\n"
    "adjrange 5 0 0 900 900 0 0 0 0\n"
    "adjrange 6 0 0 900 900 0 0 0 0\n"
    "adjrange 7 0 0 900 900 0 0 0 0\n"
    "adjrange 8 0 0 900 900 0 0 0 0\n"
    "adjrange 9 0 0 900 900 0 0 0 0\n"
    "adjrange 10 0 0 900 900 0 0 0 0\n"
    "adjrange 11 0 0 900 900 0 0 0 0\n"
    "adjrange 12 0 0 900 900 0 0 0 0\n"
    "adjrange 13 0 0 900 900 0 0 0 0\n"
    "adjrange 14 0 0 900 900 0 0 0 0\n"
    "adjrange 15 0 0 900 900 0 0 0 0\n"
    "adjrange 16 0 0 900 900 0 0 0 0\n"
    "adjrange 17 0 0 900 900 0 0 0 0\n"
    "adjrange 18 0 0 900 900 0 0 0 0\n"
    "adjrange 19 0 0 900 900 0 0 0 0\n"
    "adjrange 20 0 0 900 900 0 0 0 0\n"
    "adjrange 21 0 0 900 900 0 0 0 0\n"
    "adjrange 22 0 0 900 900 0 0 0 0\n"
    "adjrange 23 0 0 900 900 0 0 0 0\n"
    "adjrange 24 0 0 900 900 0 0 0 0\n"
    "adjrange 25 0 0 900 900 0 0 0 0\n"
    "adjrange 26 0 0 900 900 0 0 0 0\n"
    "adjrange 27 0 0 900 900 0 0 0 0\n"
    "adjrange 28 0 0 900 900 0 0 0 0\n"
    "adjrange 29 0 0 900 900 0 0 0 0\n"
    "# rxrange\n"
    "rxrange 0 1000 2000\n"
    "rxrange 1 1000 2000\n"
    "rxrange 2 1000 2000\n"
    "rxrange 3 1000 2000\n"
    "# vtxtable\n"
    "vtxtable bands 0\n"
    "vtxtable channels 0\n"
    "vtxtable powerlevels 0\n"
    "vtxtable powervalues\n"
    "vtxtable powerlabels\n"
    "# vtx\n"
    "vtx 0 0 0 0 0 900 900\n"
    "vtx 1 0 0 0 0 900 900\n"
    "vtx 2 0 0 0 0 900 900\n"
    "vtx 3 0 0 0 0 900 900\n"
    "vtx 4 0 0 0 0 900 900\n"
    "vtx 5 0 0 0 0 900 900\n"
    "vtx 6 0 0 0 0 900 900\n"
    "vtx 7 0 0 0 0 900 900\n"
    "vtx 8 0 0 0 0 900 900\n"
    "vtx 9 0 0 0 0 900 900\n"
    "# rxfail\n"
    "rxfail 0 a\n"
    "rxfail 1 a\n"
    "rxfail 2 a\n"
    "rxfail 3 a\n"
    "rxfail 4 h\n"
    "rxfail 5 h\n"
    "rxfail 6 h\n"
    "rxfail 7 h\n"
    "rxfail 8 h\n"
    "rxfail 9 h\n"
    "rxfail 10 h\n"
    "rxfail 11 h\n"
    "rxfail 12 h\n"
    "rxfail 13 h\n"
    "rxfail 14 h\n"
    "rxfail 15 h\n"
    "rxfail 16 h\n"
    "rxfail 17 h\n"
    "# master\n"
    "set gyro_hardware_lpf = NORMAL\n"
    "set gyro_lpf1_type = PT3\n"
    "set gyro_lpf1_static_hz = 0\n"
    "set gyro_lpf2_type = PT3\n"
    "set gyro_lpf2_static_hz = 250\n"
    "set gyro_notch1_hz = 85\n"
    "set gyro_notch1_cutoff = 40\n"
    "set gyro_notch2_hz = 27\n"
    "set gyro_notch2_cutoff = 24\n"
    "set gyro_calib_duration = 125\n"
    "set gyro_calib_noise_limit = 48\n"
    "set gyro_offset_yaw = 0\n"
    "set gyro_overflow_detect = ALL\n"
    "set yaw_spin_recovery = AUTO\n"
    "set yaw_spin_threshold = 1950\n"
    "set gyro_to_use = BOTH\n"
    "set dyn_notch_count = 0\n"
    "set dyn_notch_q = 300\n"
    "set dyn_notch_min_hz = 100\n"
    "set dyn_notch_max_hz = 600\n"
    "set gyro_lpf1_dyn_min_hz = 125\n"
    "set gyro_lpf1_dyn_max_hz = 250\n"
    "set gyro_lpf1_dyn_expo = 5\n"
    "set gyro_filter_debug_axis = ROLL\n"
    "set acc_hardware = AUTO\n"
    "set acc_lpf_hz = 25\n"
    "set acc_trim_pitch = 0\n"
    "set acc_trim_roll = 0\n"
    "set acc_calibration = 12,-9,8,1\n"
    "set align_mag = DEFAULT\n"
    "set mag_align_roll = 0\n"
    "set mag_align_pitch = 0\n"
    "set mag_align_yaw = 0\n"
    "set mag_bustype = I2C\n"
    "set mag_i2c_device = 2\n"
    "set mag_i2c_address = 14\n"
    "set mag_spi_device = 0\n"
    "set mag_hardware = AUTO\n"
    "set mag_calibration = 0,0,0\n"
    "set baro_bustype = I2C\n"
    "set baro_spi_device = 0\n"
    "set baro_i2c_device = 4\n"
    "set baro_i2c_address = 0\n"
    "set baro_hardware = AUTO\n"
    "set mid_rc = 1500\n"
    "set min_check = 1050\n"
    "set max_check = 1900\n"
    "set rssi_channel = 0\n"
    "set rssi_src_frame_errors = OFF\n"
    "set rssi_scale = 100\n"
    "set rssi_offset = 0\n"
    "set rssi_invert = OFF\n"
    "set rssi_src_frame_lpf_period = 30\n"
    "set rssi_smoothing = 125\n"
    "set rc_smoothing = ON\n"
    "set rc_smoothing_auto_factor = 30\n"
    "set rc_smoothing_auto_factor_throttle = 30\n"
    "set rc_smoothing_setpoint_cutoff = 0\n"
    "set rc_smoothing_feedforward_cutoff = 0\n"
    "set rc_smoothing_throttle_cutoff = 0\n"
    "set rc_smoothing_debug_axis = ROLL\n"
    "set fpv_mix_degrees = 0\n"
    "set max_aux_channels = 14\n"
    "set serialrx_provider = CRSF\n"
    "set serialrx_inverted = OFF\n"
    "set spektrum_sat_bind = 0\n"
    "set spektrum_sat_bind_autoreset = ON\n"
    "set srxl2_unit_id = 1\n"
    "set srxl2_baud_fast = ON\n"
    "set sbus_baud_fast = OFF\n"
    "set crsf_use_negotiated_baud = OFF\n"
    "set airmode_start_throttle_percent = 25\n"
    "set rx_min_usec = 885\n"
    "set rx_max_usec = 2115\n"
    "set serialrx_halfduplex = OFF\n"
    "set msp_override_channels_mask = 0\n"
    "set msp_override_failsafe = OFF\n"
    "set adc_device = 1\n"
    "set adc_vrefint_calibration = 0\n"
    "set adc_tempsensor_calibration30 = 0\n"
    "set adc_tempsensor_calibration110 = 0\n"
    "set input_filtering_mode = OFF\n"
    "set blackbox_sample_rate = 1/4\n"
    "set blackbox_device = SDCARD\n"
    "set blackbox_disable_pids = OFF\n"
    "set blackbox_disable_rc = OFF\n"
    "set blackbox_disable_setpoint = OFF\n"
    "set blackbox_disable_bat = OFF\n"
    "set blackbox_disable_mag = OFF\n"
    "set blackbox_disable_alt = OFF\n"
    "set blackbox_disable_rssi = OFF\n"
    "set blackbox_disable_gyro = OFF\n"
    "set blackbox_disable_gyrounfilt = OFF\n"
    "set blackbox_disable_acc = OFF\n"
    "set blackbox_disable_debug = OFF\n"
    "set blackbox_disable_motors = OFF\n"
    "set blackbox_disable_rpm = OFF\n"
    "set blackbox_disable_gps = OFF\n"
    "set blackbox_mode = NORMAL\n"
    "set blackbox_high_resolution = OFF\n"
    "set min_throttle = 1070\n"
    "set max_throttle = 2000\n"
    "set min_command = 1000\n"
    "set motor_kv = 1960\n"
    "set dshot_idle_value = 550\n"
    "set dshot_burst = OFF\n"
    "set dshot_bidir = OFF\n"
    "set dshot_edt = OFF\n"
    "set dshot_bitbang = AUTO\n"
    "set dshot_bitbang_timer = AUTO\n"
    "set use_unsynced_pwm = OFF\n"
    "set motor_pwm_protocol = DSHOT600\n"
    "set motor_pwm_rate = 480\n"
    "set motor_pwm_inversion = OFF\n"
    "set motor_poles = 14\n"
    "set motor_output_reordering = 2,3,0,1,4,5,6,7\n"
    "set thr_corr_value = 0\n"
    "set thr_corr_angle = 800\n"
    "set failsafe_delay = 15\n"
    "set failsafe_off_delay = 10\n"
    "set failsafe_throttle = 1000\n"
    "set failsafe_switch_mode = STAGE1\n"
    "set failsafe_throttle_low_delay = 100\n"
    "set failsafe_procedure = DROP\n"
    "set failsafe_recovery_delay = 5\n"
    "set failsafe_stick_threshold = 30\n"
    "set align_board_roll = 0\n"
    "set align_board_pitch = 0\n"
    "set align_board_yaw = 0\n"
    "set gimbal_mode = NORMAL\n"
    "set bat_capacity = 0\n"
    "set vbat_max_cell_voltage = 430\n"
    "set vbat_full_cell_voltage = 410\n"
    "set vbat_min_cell_voltage = 330\n"
    "set vbat_warning_cell_voltage = 350\n"
    "set vbat_hysteresis = 1\n"
    "set current_meter = ADC\n"
    "set battery_meter = ADC\n"
    "set vbat_detect_cell_voltage = 300\n"
    "set use_vbat_alerts = ON\n"
    "set use_cbat_alerts = OFF\n"
    "set cbat_alert_percent = 10\n"
    "set vbat_cutoff_percent = 100\n"
    "set force_battery_cell_count = 12\n"
    "set vbat_display_lpf_period = 30\n"
    "set vbat_sag_lpf_period = 2\n"
    "set ibat_lpf_period = 10\n"
    "set vbat_duration_for_warning = 0\n"
    "set vbat_duration_for_critical = 0\n"
    "set vbat_scale = 156\n"
    "set vbat_divider = 7\n"
    "set vbat_multiplier = 1\n"
    "set ibata_scale = 140\n"
    "set ibata_offset = 0\n"
    "set ibatv_scale = 0\n"
    "set ibatv_offset = 0\n"
    "set battery_continue = OFF\n"
    "set beeper_inversion = ON\n"
    "set beeper_od = OFF\n"
    "set beeper_frequency = 0\n"
    "set beeper_dshot_beacon_tone = 1\n"
    "set yaw_motors_reversed = OFF\n"
    "set mixer_type = LEGACY\n"
    "set crashflip_motor_percent = 0\n"
    "set crashflip_expo = 35\n"
    "set rpm_limit = OFF\n"
    "set rpm_limit_p = 25\n"
    "set rpm_limit_i = 10\n"
    "set rpm_limit_d = 8\n"
    "set rpm_limit_value = 18000\n"
    "set 3d_deadband_low = 1406\n"
    "set 3d_deadband_high = 1514\n"
    "set 3d_neutral = 1460\n"
    "set 3d_deadband_throttle = 50\n"
    "set 3d_limit_low = 1000\n"
    "set 3d_limit_high = 2000\n"
    "set 3d_switched_mode = OFF\n"
    "set servo_center_pulse = 1500\n"
    "set servo_pwm_rate = 50\n"
    "set servo_lowpass_hz = 0\n"
    "set tri_unarmed_servo = ON\n"
    "set channel_forwarding_start = 4\n"
    "set reboot_character = 82\n"
    "set serial_update_rate_hz = 100\n"
    "set imu_dcm_kp = 2500\n"
    "set imu_dcm_ki = 0\n"
    "set small_angle = 180\n"
    "set imu_process_denom = 2\n"
    "set mag_declination = 0\n"
    "set auto_disarm_delay = 5\n"
    "set gyro_cal_on_first_arm = OFF\n"
    "set gps_provider = UBLOX\n"
    "set gps_sbas_mode = NONE\n"
    "set gps_auto_config = ON\n"
    "set gps_auto_baud = OFF\n"
    "set gps_ublox_acquire_model = STATIONARY\n"
    "set gps_ublox_flight_model = AIRBORNE_4G\n"
    "set gps_update_rate_hz = 10\n"
    "set gps_ublox_utc_standard = AUTO\n"
    "set gps_ublox_use_galileo = OFF\n"
    "set gps_set_home_point_once = OFF\n"
    "set gps_use_3d_speed = OFF\n"
    "set gps_sbas_integrity = OFF\n"
    "set gps_nmea_custom_commands = -\n"
    "set gps_rescue_min_start_dist = 15\n"
    "set gps_rescue_alt_mode = MAX_ALT\n"
    "set gps_rescue_initial_climb = 10\n"
    "set gps_rescue_ascend_rate = 750\n"
    "set gps_rescue_return_alt = 30\n"
    "set gps_rescue_ground_speed = 750\n"
    "set gps_rescue_max_angle = 45\n"
    "set gps_rescue_roll_mix = 150\n"
    "set gps_rescue_pitch_cutoff = 75\n"
    "set gps_rescue_imu_yaw_gain = 10\n"
    "set gps_rescue_descent_dist = 20\n"
    "set gps_rescue_descend_rate = 150\n"
    "set gps_rescue_landing_alt = 4\n"
    "set gps_rescue_disarm_threshold = 20\n"
    "set gps_rescue_throttle_min = 1100\n"
    "set gps_rescue_throttle_max = 1700\n"
    "set gps_rescue_throttle_hover = 1275\n"
    "set gps_rescue_sanity_checks = RESCUE_SANITY_FS_ONLY\n"
    "set gps_rescue_min_sats = 8\n"
    "set gps_rescue_allow_arming_without_fix = OFF\n"
    "set gps_rescue_throttle_p = 15\n"
    "set gps_rescue_throttle_i = 15\n"
    "set gps_rescue_throttle_d = 20\n"
    "set gps_rescue_velocity_p = 8\n"
    "set gps_rescue_velocity_i = 40\n"
    "set gps_rescue_velocity_d = 12\n"
    "set gps_rescue_yaw_p = 20\n"
    "set gps_rescue_use_mag = ON\n"
    "set deadband = 0\n"
    "set yaw_deadband = 0\n"
    "set yaw_control_reversed = OFF\n"
    "set pid_process_denom = 16\n"
    "set runaway_takeoff_prevention = ON\n"
    "set runaway_takeoff_deactivate_delay = 500\n"
    "set runaway_takeoff_deactivate_throttle_percent = 20\n"
    "set simplified_gyro_filter = ON\n"
    "set simplified_gyro_filter_multiplier = 50\n"
    "set tlm_inverted = OFF\n"
    "set tlm_halfduplex = ON\n"
    "set frsky_default_lat = 0\n"
    "set frsky_default_long = 0\n"
    "set frsky_gps_format = 0\n"
    "set frsky_unit = METRIC\n"
    "set frsky_vfas_precision = 0\n"
    "set hott_alarm_int = 5\n"
    "set pid_in_tlm = OFF\n"
    "set report_cell_voltage = OFF\n"
    "set ibus_sensor = 1,2,3,0,0,0,0,0,0,0,0,0,0,0,0\n"
    "set mavlink_mah_as_heading_divisor = 0\n"
    "set telemetry_disabled_voltage = OFF\n"
    "set telemetry_disabled_current = OFF\n"
    "set telemetry_disabled_fuel = OFF\n"
    "set telemetry_disabled_mode = OFF\n"
    "set telemetry_disabled_acc_x = OFF\n"
    "set telemetry_disabled_acc_y = OFF\n"
    "set telemetry_disabled_acc_z = OFF\n"
    "set telemetry_disabled_pitch = OFF\n"
    "set telemetry_disabled_roll = OFF\n"
    "set telemetry_disabled_heading = OFF\n"
    "set telemetry_disabled_altitude = OFF\n"
    "set telemetry_disabled_vario = OFF\n"
    "set telemetry_disabled_lat_long = OFF\n"
    "set telemetry_disabled_ground_speed = OFF\n"
    "set telemetry_disabled_distance = OFF\n"
    "set telemetry_disabled_esc_current = ON\n"
    "set telemetry_disabled_esc_voltage = ON\n"
    "set telemetry_disabled_esc_rpm = ON\n"
    "set telemetry_disabled_esc_temperature = ON\n"
    "set telemetry_disabled_temperature = OFF\n"
    "set telemetry_disabled_cap_used = ON\n"
    "set ledstrip_visual_beeper = OFF\n"
    "set ledstrip_visual_beeper_color = WHITE\n"
    "set ledstrip_grb_rgb = GRB\n"
    "set ledstrip_profile = STATUS\n"
    "set ledstrip_race_color = ORANGE\n"
    "set ledstrip_beacon_color = WHITE\n"
    "set ledstrip_beacon_period_ms = 500\n"
    "set ledstrip_beacon_percent = 50\n"
    "set ledstrip_beacon_armed_only = OFF\n"
    "set ledstrip_brightness = 100\n"
    "set ledstrip_rainbow_delta = 0\n"
    "set ledstrip_rainbow_freq = 120\n"
    "set sdcard_detect_inverted = OFF\n"
    "set sdcard_mode = SDIO\n"
    "set sdcard_spi_bus = 0\n"
    "set sdio_clk_bypass = OFF\n"
    "set sdio_use_cache = OFF\n"
    "set sdio_use_4bit_width = ON\n"
    "set sdio_device = 1\n"
    "set osd_units = METRIC\n"
    "set osd_warn_bitmask = 270335\n"
    "set osd_rssi_alarm = 20\n"
    "set osd_link_quality_alarm = 80\n"
    "set osd_rssi_dbm_alarm = -60\n"
    "set osd_rsnr_alarm = 4\n"
    "set osd_cap_alarm = 2200\n"
    "set osd_alt_alarm = 100\n"
    "set osd_distance_alarm = 0\n"
    "set osd_esc_temp_alarm = 0\n"
    "set osd_esc_rpm_alarm = -1\n"
    "set osd_esc_current_alarm = -1\n"
    "set osd_core_temp_alarm = 70\n"
    "set osd_ah_max_pit = 20\n"
    "set osd_ah_max_rol = 40\n"
    "set osd_ah_invert = OFF\n"
    "set osd_logo_on_arming = OFF\n"
    "set osd_logo_on_arming_duration = 5\n"
    "set osd_use_quick_menu = ON\n"
    "set osd_show_spec_prearm = OFF\n"
    "set osd_tim1 = 2560\n"
    "set osd_tim2 = 2561\n"
    "set osd_vbat_pos = 2379\n"
    "set osd_rssi_pos = 2103\n"
    "set osd_link_quality_pos = 2082\n"
    "set osd_link_tx_power_pos = 341\n"
    "set osd_rssi_dbm_pos = 2114\n"
    "set osd_rsnr_pos = 341\n"
    "set osd_tim_1_pos = 341\n"
    "set osd_tim_2_pos = 341\n"
    "set osd_remaining_time_estimate_pos = 341\n"
    "set osd_flymode_pos = 2509\n"
    "set osd_anti_gravity_pos = 341\n"
    "set osd_g_force_pos = 341\n"
    "set osd_throttle_pos = 2454\n"
    "set osd_vtx_channel_pos = 341\n"
    "set osd_crosshairs_pos = 2285\n"
    "set osd_ah_sbar_pos = 2286\n"
    "set osd_ah_pos = 2158\n"
    "set osd_current_pos = 2465\n"
    "set osd_mah_drawn_pos = 2435\n"
    "set osd_wh_drawn_pos = 341\n"
    "set osd_motor_diag_pos = 341\n"
    "set osd_craft_name_pos = 341\n"
    "set osd_pilot_name_pos = 2090\n"
    "set osd_gps_speed_pos = 341\n"
    "set osd_gps_lon_pos = 341\n"
    "set osd_gps_lat_pos = 341\n"
    "set osd_gps_sats_pos = 341\n"
    "set osd_home_dir_pos = 341\n"
    "set osd_home_dist_pos = 341\n"
    "set osd_flight_dist_pos = 341\n"
    "set osd_compass_bar_pos = 341\n"
    "set osd_altitude_pos = 2486\n"
    "set osd_pid_roll_pos = 341\n"
    "set osd_pid_pitch_pos = 341\n"
    "set osd_pid_yaw_pos = 341\n"
    "set osd_debug_pos = 341\n"
    "set osd_power_pos = 341\n"
    "set osd_pidrate_profile_pos = 341\n"
    "set osd_warnings_pos = 14730\n"
    "set osd_avg_cell_voltage_pos = 2498\n"
    "set osd_pit_ang_pos = 341\n"
    "set osd_rol_ang_pos = 341\n"
    "set osd_battery_usage_pos = 341\n"
    "set osd_disarmed_pos = 341\n"
    "set osd_nheading_pos = 341\n"
    "set osd_up_down_reference_pos = 312\n"
    "set osd_ready_mode_pos = 341\n"
    "set osd_nvario_pos = 341\n"
    "set osd_esc_tmp_pos = 341\n"
    "set osd_esc_rpm_pos = 341\n"
    "set osd_esc_rpm_freq_pos = 341\n"
    "set osd_rtc_date_time_pos = 341\n"
    "set osd_adjustment_range_pos = 341\n"
    "set osd_flip_arrow_pos = 341\n"
    "set osd_core_temp_pos = 341\n"
    "set osd_log_status_pos = 341\n"
    "set osd_stick_overlay_left_pos = 341\n"
    "set osd_stick_overlay_right_pos = 341\n"
    "set osd_stick_overlay_radio_mode = 2\n"
    "set osd_rate_profile_name_pos = 341\n"
    "set osd_pid_profile_name_pos = 341\n"
    "set osd_profile_name_pos = 341\n"
    "set osd_rcchannels_pos = 341\n"
    "set osd_camera_frame_pos = 142\n"
    "set osd_efficiency_pos = 341\n"
    "set osd_total_flights_pos = 341\n"
    "set osd_aux_pos = 341\n"
    "set osd_sys_goggle_voltage_pos = 341\n"
    "set osd_sys_vtx_voltage_pos = 341\n"
    "set osd_sys_bitrate_pos = 341\n"
    "set osd_sys_delay_pos = 341\n"
    "set osd_sys_distance_pos = 341\n"
    "set osd_sys_lq_pos = 341\n"
    "set osd_sys_goggle_dvr_pos = 341\n"
    "set osd_sys_vtx_dvr_pos = 341\n"
    "set osd_sys_warnings_pos = 341\n"
    "set osd_sys_vtx_temp_pos = 341\n"
    "set osd_sys_fan_speed_pos = 341\n"
    "set osd_stat_bitmask = 2107234\n"
    "set osd_profile = 1\n"
    "set osd_profile_1_name = -\n"
    "set osd_profile_2_name = -\n"
    "set osd_profile_3_name = -\n"
    "set osd_gps_sats_show_pdop = OFF\n"
    "set osd_displayport_device = AUTO\n"
    "set osd_rcchannels = -1,-1,-1,-1\n"
    "set osd_camera_frame_width = 24\n"
    "set osd_camera_frame_height = 11\n"
    "set osd_stat_avg_cell_value = OFF\n"
    "set osd_framerate_hz = 12\n"
    "set osd_menu_background = TRANSPARENT\n"
    "set osd_aux_channel = 1\n"
    "set osd_aux_scale = 200\n"
    "set osd_aux_symbol = 65\n"
    "set osd_canvas_width = 30\n"
    "set osd_canvas_height = 16\n"
    "set osd_craftname_msgs = OFF\n"
    "set task_statistics = ON\n"
    "set debug_mode = NONE\n"
    "set rate_6pos_switch = OFF\n"
    "set pwr_on_arm_grace = 5\n"
    "set enable_stick_arming = OFF\n"
    "set vtx_band = 0\n"
    "set vtx_channel = 0\n"
    "set vtx_power = 0\n"
    "set vtx_low_power_disarm = OFF\n"
    "set vtx_softserial_alt = OFF\n"
    "set vtx_freq = 0\n"
    "set vtx_pit_mode_freq = 0\n"
    "set vtx_halfduplex = ON\n"
    "set vtx_spi_bus = 0\n"
    "set vcd_video_system = PAL\n"
    "set vcd_h_offset = 0\n"
    "set vcd_v_offset = 0\n"
    "set max7456_clock = NOMINAL\n"
    "set max7456_spi_bus = 2\n"
    "set max7456_preinit_opu = OFF\n"
    "set displayport_msp_col_adjust = 0\n"
    "set displayport_msp_row_adjust = 0\n"
    "set displayport_msp_fonts = 0,1,2,3\n"
    "set displayport_msp_use_device_blink = OFF\n"
    "set displayport_max7456_col_adjust = 0\n"
    "set displayport_max7456_row_adjust = 0\n"
    "set displayport_max7456_inv = OFF\n"
    "set displayport_max7456_blk = 0\n"
    "set displayport_max7456_wht = 2\n"
    "set esc_sensor_halfduplex = OFF\n"
    "set esc_sensor_current_offset = 0\n"
    "set led_inversion = 0\n"
    "set dashboard_i2c_bus = 0\n"
    "set dashboard_i2c_addr = 60\n"
    "set rangefinder_hardware = NONE\n"
    "set pinio_config = 129,1,1,1\n"
    "set pinio_box = 40,41,255,255\n"
    "set usb_hid_cdc = OFF\n"
    "set usb_msc_pin_pullup = ON\n"
    "set rcdevice_init_dev_attempts = 6\n"
    "set rcdevice_init_dev_attempt_interval = 1000\n"
    "set rcdevice_protocol_version = 0\n"
    "set rcdevice_feature = 0\n"
    "set gyro_1_bustype = SPI\n"
    "set gyro_1_spibus = 1\n"
    "set gyro_1_i2cBus = 0\n"
    "set gyro_1_i2c_address = 0\n"
    "set gyro_1_sensor_align = CW0\n"
    "set gyro_1_align_roll = 0\n"
    "set gyro_1_align_pitch = 0\n"
    "set gyro_1_align_yaw = 0\n"
    "set gyro_2_bustype = SPI\n"
    "set gyro_2_spibus = 4\n"
    "set gyro_2_i2cBus = 0\n"
    "set gyro_2_i2c_address = 0\n"
    "set gyro_2_sensor_align = CW270\n"
    "set gyro_2_align_roll = 0\n"
    "set gyro_2_align_pitch = 0\n"
    "set gyro_2_align_yaw = 2700\n"
    "set i2c1_pullup = OFF\n"
    "set i2c1_clockspeed_khz = 800\n"
    "set i2c2_pullup = OFF\n"
    "set i2c2_clockspeed_khz = 800\n"
    "set i2c3_pullup = OFF\n"
    "set i2c3_clockspeed_khz = 800\n"
    "set i2c4_pullup = OFF\n"
    "set i2c4_clockspeed_khz = 800\n"
    "set scheduler_relax_rx = 25\n"
    "set scheduler_relax_osd = 25\n"
    "set cpu_late_limit_permille = 10\n"
    "set serialmsp_halfduplex = OFF\n"
    "set timezone_offset_minutes = 0\n"
    "set rpm_filter_harmonics = 3\n"
    "set rpm_filter_weights = 100,100,100\n"
    "set rpm_filter_q = 500\n"
    "set rpm_filter_min_hz = 100\n"
    "set rpm_filter_fade_range_hz = 50\n"
    "set rpm_filter_lpf_hz = 150\n"
    "set stats_min_armed_time_s = -1\n"
    "set stats_total_flights = 0\n"
    "set stats_total_time_s = 0\n"
    "set stats_total_dist_m = 0\n"
    "set stats_mah_used = 0\n"
    "set craft_name = VT40-2 V2\n"
    "set pilot_name = VT40-2 V2\n"
    "set altitude_source = DEFAULT\n"
    "set altitude_prefer_baro = 100\n"
    "set altitude_lpf = 300\n"
    "set altitude_d_lpf = 100\n"
    "set box_user_1_name = -\n"
    "set box_user_2_name = -\n"
    "set box_user_3_name = -\n"
    "set box_user_4_name = -\n"
    "profile 0\n"
    "# profile 0\n"
    "set profile_name = -\n"
    "set dterm_lpf1_dyn_min_hz = 75\n"
    "set dterm_lpf1_dyn_max_hz = 150\n"
    "set dterm_lpf1_dyn_expo = 5\n"
    "set dterm_lpf1_type = PT1\n"
    "set dterm_lpf1_static_hz = 75\n"
    "set dterm_lpf2_type = PT1\n"
    "set dterm_lpf2_static_hz = 150\n"
    "set dterm_notch_hz = 0\n"
    "set dterm_notch_cutoff = 0\n"
    "set vbat_sag_compensation = 0\n"
    "set pid_at_min_throttle = ON\n"
    "set anti_gravity_gain = 0\n"
    "set anti_gravity_cutoff_hz = 5\n"
    "set anti_gravity_p_gain = 100\n"
    "set acc_limit_yaw = 0\n"
    "set acc_limit = 0\n"
    "set crash_dthreshold = 50\n"
    "set crash_gthreshold = 400\n"
    "set crash_setpoint_threshold = 350\n"
    "set crash_time = 500\n"
    "set crash_delay = 0\n"
    "set crash_recovery_angle = 10\n"
    "set crash_recovery_rate = 100\n"
    "set crash_limit_yaw = 200\n"
    "set crash_recovery = OFF\n"
    "set iterm_rotation = OFF\n"
    "set iterm_relax = RP\n"
    "set iterm_relax_type = GYRO\n"
    "set iterm_relax_cutoff = 5\n"
    "set iterm_windup = 85\n"
    "set iterm_limit = 400\n"
    "set pidsum_limit = 500\n"
    "set pidsum_limit_yaw = 400\n"
    "set yaw_lowpass_hz = 100\n"
    "set throttle_boost = 5\n"
    "set throttle_boost_cutoff = 15\n"
    "set p_pitch = 40\n"
    "set i_pitch = 36\n"
    "set d_pitch = 78\n"
    "set f_pitch = 162\n"
    "set p_roll = 40\n"
    "set i_roll = 31\n"
    "set d_roll = 70\n"
    "set f_roll = 156\n"
    "set p_yaw = 30\n"
    "set i_yaw = 40\n"
    "set d_yaw = 0\n"
    "set f_yaw = 156\n"
    "set angle_p_gain = 50\n"
    "set angle_feedforward = 50\n"
    "set angle_feedforward_smoothing_ms = 80\n"
    "set angle_limit = 60\n"
    "set angle_earth_ref = 100\n"
    "set horizon_level_strength = 75\n"
    "set horizon_limit_sticks = 75\n"
    "set horizon_limit_degrees = 135\n"
    "set horizon_ignore_sticks = OFF\n"
    "set horizon_delay_ms = 500\n"
    "set abs_control_gain = 0\n"
    "set abs_control_limit = 90\n"
    "set abs_control_error_limit = 20\n"
    "set abs_control_cutoff = 11\n"
    "set use_integrated_yaw = OFF\n"
    "set integrated_yaw_relax = 200\n"
    "set d_min_roll = 0\n"
    "set d_min_pitch = 0\n"
    "set d_min_yaw = 0\n"
    "set d_max_gain = 25\n"
    "set d_max_advance = 20\n"
    "set motor_output_limit = 100\n"
    "set auto_profile_cell_count = 0\n"
    "set launch_control_mode = NORMAL\n"
    "set launch_trigger_allow_reset = ON\n"
    "set launch_trigger_throttle_percent = 20\n"
    "set launch_angle_limit = 0\n"
    "set launch_control_gain = 40\n"
    "set thrust_linear = 0\n"
    "set transient_throttle_limit = 0\n"
    "set feedforward_transition = 0\n"
    "set feedforward_averaging = 3_POINT\n"
    "set feedforward_smooth_factor = 42\n"
    "set feedforward_jitter_factor = 4\n"
    "set feedforward_boost = 15\n"
    "set feedforward_max_rate_limit = 90\n"
    "set dyn_idle_min_rpm = 0\n"
    "set dyn_idle_p_gain = 50\n"
    "set dyn_idle_i_gain = 50\n"
    "set dyn_idle_d_gain = 50\n"
    "set dyn_idle_max_increase = 150\n"
    "set dyn_idle_start_increase = 50\n"
    "set level_race_mode = OFF\n"
    "set simplified_pids_mode = OFF\n"
    "set simplified_master_multiplier = 100\n"
    "set simplified_i_gain = 100\n"
    "set simplified_d_gain = 100\n"
    "set simplified_pi_gain = 100\n"
    "set simplified_dmax_gain = 100\n"
    "set simplified_feedforward_gain = 100\n"
    "set simplified_pitch_d_gain = 100\n"
    "set simplified_pitch_pi_gain = 100\n"
    "set simplified_dterm_filter = ON\n"
    "set simplified_dterm_filter_multiplier = 100\n"
    "set tpa_mode = D\n"
    "set tpa_rate = 65\n"
    "set tpa_breakpoint = 1350\n"
    "set tpa_low_rate = 20\n"
    "set tpa_low_breakpoint = 1050\n"
    "set tpa_low_always = OFF\n"
    "set ez_landing_threshold = 25\n"
    "set ez_landing_limit = 15\n"
    "set ez_landing_speed = 50\n"
    "rateprofile 0\n"
    "# rateprofile 0\n"
    "set rateprofile_name = -\n"
    "set thr_mid = 50\n"
    "set thr_expo = 0\n"
    "set rates_type = ACTUAL\n"
    "set quickrates_rc_expo = OFF\n"
    "set roll_rc_rate = 7\n"
    "set pitch_rc_rate = 7\n"
    "set yaw_rc_rate = 7\n"
    "set roll_expo = 0\n"
    "set pitch_expo = 0\n"
    "set yaw_expo = 0\n"
    "set roll_srate = 67\n"
    "set pitch_srate = 67\n"
    "set yaw_srate = 67\n"
    "set throttle_limit_type = OFF\n"
    "set throttle_limit_percent = 100\n"
    "set roll_rate_limit = 1998\n"
    "set pitch_rate_limit = 1998\n"
    "set yaw_rate_limit = 1998\n"
    "# end the command batch\n"
    "batch end\n"
    "\0";
